# Generated by Django 2.0.1 on 2018-01-31 13:51

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180131_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=posts.models.upload_to, verbose_name='Image'),
        ),
    ]
