# Generated by Django 2.0.1 on 2018-01-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Telefon Numarası')),
                ('gender', models.CharField(blank=True, choices=[('E', 'Man'), ('K', 'Woman'), ('O', 'Other')], default=3, max_length=1, verbose_name='Cinsiyet')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Hakkında')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('profile_photo', models.ImageField(blank=True, upload_to=users.models.upload_to, verbose_name='Profil Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Bilgileri',
                'verbose_name_plural': 'Kullanıcı Bilgileri',
            },
        ),
    ]
