# Generated by Django 2.0.1 on 2018-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.CharField(choices=[('P', 'PUBLIC'), ('F', 'FOLLOWING')], default=1, max_length=1, verbose_name='Profil Durumu'),
        ),
    ]
